
CREATE TABLE `xl_inpatient_check` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `report_number` varchar(128) NOT NULL COMMENT '检验报告单号，对应医院系统中的唯一识别号或流水号',
  `hospital_id` varchar(128) NOT NULL COMMENT '指医疗机构执业许可证上面的 机构代码。由 22 位数字(或英 文字母)组成，包括 9 位组织 机构代码和 13 位机构属性代码',
  `hospital_name` varchar(128) NOT NULL COMMENT '指患者住院诊疗所在的医疗机构名称，按照《医疗机构执业许可证》登记的机构名称填写',
  `inpatient_id` varchar(128) NOT NULL COMMENT '患者的病案号，指本医疗机构为患者住院病案设置的唯一性编码。原则上，同一患者在同一医疗机构多次住院应当使用同一病案号',
  `inpatient_serial_num` varchar(128) NOT NULL COMMENT '患者的就诊流水号，多次住院时，每次的就诊流水号不一样',
  `name` varchar(50) NOT NULL COMMENT '患者姓名',
  `sex` tinyint(4) NOT NULL COMMENT '患者性别，0：未知的性别；1：男；2：女',
  `age` int(11) NOT NULL COMMENT '单位(岁)指患者入院时的实足年龄。患者出生后按照日历计算的历法年龄，应以实足年龄的相应整数填写(小于 1 周岁的年龄此处传空)',
  `check_date` datetime NOT NULL COMMENT '报告日期，时间格式为 yyyy- MM-dd HH:mm:ss',
  `check_item_code` varchar(20) NOT NULL COMMENT '检验项目代码',
  `check_item_name` varchar(40) NOT NULL COMMENT '检验项目名称',
  `check_detail_item_code` varchar(20) NOT NULL COMMENT '检验明细项目代码',
  `check_detail_item_name` varchar(40) NOT NULL COMMENT '检验明细项目名称',
  `perform_office_name` varchar(40) DEFAULT NULL COMMENT '执行检验科室名称',
  `perform_doctor_name` varchar(40) NOT NULL COMMENT '执行检验医师姓名',
  `apply_office_name` varchar(40) NOT NULL COMMENT '申请检验科室名称',
  `apply_doctor_name` varchar(40) NOT NULL COMMENT '申请检验医师姓名',
  `check_result` varchar(20) NOT NULL COMMENT '检验结果值',
  `check_result_unit` varchar(20) DEFAULT NULL COMMENT '检验结果单位，如果检验结果为数字，则检验结果单位必填，如果检验结果为阴性/阳性这样的记录，则检验结果单位不填',
  `reference_value` varchar(40) NOT NULL COMMENT '检验明细项目参考值',
  `is_normal` tinyint(4) DEFAULT NULL COMMENT '检查结果是否正常，正常填0，不正常填1。',
  `xl_insert_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `xl_change_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COMMENT='住院检验信息';

CREATE TABLE `xl_inpatient_examination` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `last_update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `report_number` varchar(128) NOT NULL COMMENT '检查报告单号，对应医院系统中的唯一识别号或流水号',
  `hospital_id` varchar(128) NOT NULL COMMENT '指医疗机构执业许可证上面的 机构代码。由 22 位数字(或英 文字母)组成，包括 9 位组织 机构代码和 13 位机构属性代码',
  `hospital_name` varchar(128) NOT NULL COMMENT '指患者住院诊疗所在的医疗机构名称，按照《医疗机构执业许可证》登记的机构名称填写',
  `inpatient_id` varchar(128) NOT NULL COMMENT '患者的病案号，指本医疗机构为患者住院病案设置的唯一性编码。原则上，同一患者在同一医疗机构多次住院应当使用同一病案号',
  `inpatient_serial_num` varchar(128) NOT NULL COMMENT '患者的就诊流水号，多次住院时，每次的就诊流水号不一样',
  `name` varchar(50) NOT NULL COMMENT '患者姓名',
  `sex` tinyint(4) NOT NULL COMMENT '患者性别，0：未知的性别；1：男；2：女',
  `age` int(11) NOT NULL COMMENT '单位(岁)指患者入院时的实足年龄。患者出生后按照日历计算的历法年龄，应以实足年龄的相应整数填写(小于 1 周岁的年龄此处传空)',
  `examine_date` datetime NOT NULL COMMENT '报告日期，时间格式为 yyyy- MM-dd HH:mm:ss',
  `apply_doctor_name` varchar(50) NOT NULL COMMENT '开具检查申请的医师姓名',
  `perform_doctor_name` varchar(50) DEFAULT NULL COMMENT '执行检查的医师姓名',
  `examination_category_code` varchar(20) DEFAULT NULL COMMENT '检查项目类型代码，1：心电图；2：X线；3：MRI；4：CT；5：心脏超声；6：食道超声；7：血管超声；8：其它超声',
  `apply_office_name` varchar(40) DEFAULT NULL COMMENT '申请检查科室名称',
  `examination_part_name` varchar(255) DEFAULT NULL COMMENT '检查部位名称',
  `examination_method_name` varchar(255) DEFAULT NULL COMMENT '检查方式名称',
  `image_description` text COMMENT '影像描述，详细的影像信息描述。',
  `examination_result` text NOT NULL COMMENT '检查结果',
  `image_url` text COMMENT '影像文件URL',
  `xl_insert_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `xl_change_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COMMENT='住院检查信息';


CREATE TABLE `xl_inpatient_record` (
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `hospital_id` varchar(128) DEFAULT NULL COMMENT '指医疗机构执业许可证上面的 机构代码。由 22 位数字(或 英文字母)组成，包括 9 位组织机构代码和13位机构属性代码',
  `hospital_name` varchar(128) DEFAULT NULL COMMENT '指患者住院诊疗所在的医疗机构名称，按照《医疗机构执业许可证》登记的机构名称填写',
  `medical_card_num` varchar(128) DEFAULT NULL COMMENT '医疗保险手册卡号',
  `health_card_num` varchar(128) DEFAULT NULL COMMENT '在已统一发放“中华人民共和国居民健康卡”的地区填写健康卡号码，尚未发放“健康卡”的地区填写“就医卡号”等患者识别码或暂不填写',
  `pay_type` tinyint(4) DEFAULT NULL COMMENT '医疗付费方式，1：城镇职工基本医疗保险；2：城镇居民基本医疗保险；3：新型农村合作医疗；4：贫困救助；5：商业医疗保险；6：全公费；7：全自费；8：其他社会保险；9：其他',
  `admission_num` int(11) DEFAULT NULL COMMENT '指患者在本医疗机构住院诊治的次数',
  `inpatient_id` varchar(128) NOT NULL COMMENT '患者的病案号，指本医疗机构为患者住院病案设置的唯一性编码。原则上，同一患者在同一医疗机构多次住院应当使用同一病案号',
  `inpatient_serial_num` varchar(128) DEFAULT NULL COMMENT '患者的就诊流水号，多次住院时，每次的就诊流水号不一样',
  `name` varchar(128) DEFAULT NULL COMMENT '患者姓名',
  `sex` tinyint(4) DEFAULT NULL COMMENT '患者性别，0：未知的性别；1：男；2：女',
  `birthday` date DEFAULT NULL COMMENT '出生日期，格式必须为 yyyy-MM-dd，形如2008-07-04',
  `age` int(11) DEFAULT NULL COMMENT '单位(岁)指患者入院时的实足年龄。患者出生后按照日历计算的历法年龄，应以实足年龄的相应整数填写(小于 1 周岁的年龄此处传空)',
  `marital_status` tinyint(4) DEFAULT NULL COMMENT '婚姻状况，1：未婚；2：已婚；3：丧偶；4：离婚；9：其他',
  `profession` tinyint(4) DEFAULT NULL COMMENT '职业，11：国家公务员；13：专业技术人员；17：职员；21：企业管理人员；24：工人；27：农民；31：学生；37：现役军人；51：自由职业者；54：个体经营者；70：无业人员；80：退(离)休人员；90：其他',
  `birthplace` varchar(512) DEFAULT NULL COMMENT '出生地的完整地址',
  `birth_province` varchar(50) DEFAULT NULL COMMENT '出生省份',
  `birth_city` varchar(50) DEFAULT NULL COMMENT '出生城市',
  `birth_county` varchar(50) DEFAULT NULL COMMENT '出生区或县',
  `nationality` varchar(20) DEFAULT NULL COMMENT '民族',
  `country` varchar(40) DEFAULT NULL COMMENT '国籍',
  `id_card_num` varchar(40) DEFAULT NULL COMMENT '可填写大陆身份证号码、军官证、港澳通行证等有效证件号码。除无身份证或因其他特殊原因无法采集者外，住院患者入院时要如实填写 18 位身份证号',
  `address` varchar(255) DEFAULT NULL COMMENT '现住址',
  `post_code` varchar(6) DEFAULT NULL COMMENT '现住址邮政编码',
  `mobile` varchar(40) DEFAULT NULL COMMENT '手机号码',
  `work_unit_addr` varchar(255) DEFAULT NULL COMMENT '工作单位名称及地址',
  `registered_addr` varchar(255) DEFAULT NULL COMMENT '户口地址',
  `contact_name` varchar(50) DEFAULT NULL COMMENT '联系人姓名',
  `relationship` tinyint(4) DEFAULT NULL COMMENT '与患者关系，1：配偶；2：子；3：女；4：孙子、孙女或外孙子、外孙女；5：父母；6：祖父母或外祖父母；7：兄、弟、姐、妹；8：其他',
  `contact_addr` varchar(255) DEFAULT NULL COMMENT '联系人地址',
  `contact_mobile` varchar(40) DEFAULT NULL COMMENT '联系人电话',
  `admission_type` tinyint(4) DEFAULT NULL COMMENT '入院途径，1：急诊；2：门诊；3：其他医疗机构转入；4：其他',
  `admission_date` datetime DEFAULT NULL COMMENT '入院日期，时间格式为 yyyy- MM-dd HH:mm:ss',
  `admission_office` varchar(255) DEFAULT NULL COMMENT '入院科室',
  `discharge_date` datetime DEFAULT NULL COMMENT '出院日期，时间格式为 yyyy- MM-dd HH:mm:ss',
  `discharge_office` varchar(255) DEFAULT NULL COMMENT '出院科室',
  `hospital_stay` int(11) DEFAULT NULL COMMENT '住院天数;入院日与出院日只 计算一天，例如:2011 年 6 月 12 日入院，2011 年 6 月 15 日出院，计住院天数为 3 天',
  `clinic_diagnosis_code` varchar(20) DEFAULT NULL COMMENT '诊断编码。编码采 用北京版、全国版 ICD-10，见 附件北京版、全国版 RC020- ICD-10 诊断编码',
  `clinic_diagnosis_desc` varchar(100) DEFAULT NULL COMMENT '诊断描述',
  `is_zlfs_yw` char(1) DEFAULT NULL COMMENT '治疗方式：药物',
  `is_zlfs_spxr` char(1) DEFAULT NULL COMMENT '治疗方式：射频消融',
  `is_zlfs_ldxr` char(1) DEFAULT NULL COMMENT '治疗方式：冷冻消融',
  `is_zlfs_zxefd` char(1) DEFAULT NULL COMMENT '治疗方式：左心耳封堵',
  `is_zlfs_qbq` char(1) DEFAULT NULL COMMENT '治疗方式：起搏器',
  `is_zlfs_wkss` char(1) DEFAULT NULL COMMENT '治疗方式：外科手术',
  `knyw` varchar(128) DEFAULT NULL COMMENT '抗凝药物',
  `hospital_code` varchar(1000) DEFAULT NULL COMMENT '医院代码',
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='住院信息的病案首页数据';


CREATE TABLE `xl_operation_record` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `operation_serial_num` varchar(128) NOT NULL COMMENT '手术流水号，对应医院系统中的唯一识别号或流水号',
  `hospital_id` varchar(128) NOT NULL COMMENT '指医疗机构执业许可证上面的 机构代码。由 22 位数字(或英 文字母)组成，包括 9 位组织 机构代码和 13 位机构属性代码',
  `hospital_name` varchar(128) NOT NULL COMMENT '指患者住院诊疗所在的医疗机构名称，按照《医疗机构执业许可证》登记的机构名称填写',
  `inpatient_id` varchar(128) NOT NULL COMMENT '患者的病案号，指本医疗机构为患者住院病案设置的唯一性编码。原则上，同一患者在同一医疗机构多次住院应当使用同一病案号',
  `inpatient_serial_num` varchar(128) NOT NULL COMMENT '患者的就诊流水号，多次住院时，每次的就诊流水号不一样',
  `id_card_num` varchar(1000) DEFAULT NULL COMMENT '患者身份证号',
  `name` varchar(50) NOT NULL COMMENT '患者姓名',
  `sex` tinyint(4) NOT NULL COMMENT '患者性别，1：男；2：女;3: 其他',
  `age` int(11) NOT NULL COMMENT '单位(岁)指患者入院时的实足年龄。患者出生后按照日历计算的历法年龄，应以实足年龄的相应整数填写(小于 1 周岁的年龄此处传空)',
  `office` varchar(40) NOT NULL COMMENT '执行手术科室名称',
  `operation_time` datetime NOT NULL COMMENT '手术执行时间，格式为 yyyy-MM-dd',
  `operator` varchar(40) NOT NULL COMMENT '术者',
  `first_assistant` varchar(40) DEFAULT NULL COMMENT '第一助手',
  `second_assistant` varchar(40) DEFAULT NULL COMMENT '第二助手',
  `operation_name` varchar(128) NOT NULL COMMENT '手术/操作名称',
  `anesthesia_method` text COMMENT '麻醉方式，多个麻醉方式之间以英文格式“,”分隔',
  `anesthesia_physician` varchar(40) DEFAULT NULL COMMENT '麻醉医师',
  `diagnosis_before_operation` varchar(255) NOT NULL COMMENT '术前诊断，多个术前诊断之间以英文格式","分隔',
  `diagnosis_after_operation` varchar(255) NOT NULL COMMENT '术后诊断，多个术后诊断之间以英文格式","分隔',
  `intraoperatve_blood_loss` int(11) DEFAULT NULL COMMENT '术中出血量，单位ml',
  `blood_transfusion_type` varchar(40) DEFAULT NULL COMMENT '输血种类',
  `blood_transfusion_amount` varchar(40) DEFAULT NULL COMMENT '输血量',
  `blood_transfusion_reaction` varchar(40) DEFAULT NULL COMMENT '输血反应',
  `surgical_procedure` text NOT NULL COMMENT '手术经过，手术经过的详细描述',
  `postoperative_situation` varchar(255) NOT NULL COMMENT '术后情况',
  `recorder` varchar(40) DEFAULT NULL COMMENT '记录者',
  `hospital_code` varchar(1000) DEFAULT NULL COMMENT '医院代码',
  PRIMARY KEY (`id`,`inpatient_serial_num`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



